Neuron

In [1]:
inputs=[1.2,5.1,2.1]
weights=[3.1,2.1,8.7]
bias=3

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

35.7


In [2]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

2.3


In [3]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1]
bias=2

output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias
print(output)

4.8


In [4]:
inputs=[1,2,3,2.5]
weights1=[0.2,0.8,-0.5,1]
weights2=[0.5,-0.91,0.26,-0.5]
weights3=[-0.26,-0.27,0.17,0.87]
bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
        

print(output)

[4.8, 1.21, 2.385]


In [5]:
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
     
layer_outputs=[]
for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output=0
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output+= n_input*weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


In [1]:
import numpy as np

In [7]:
inputs=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1]
bias=[2]

output=np.dot(weights,inputs)+bias
print(output)

[4.8]


In [8]:
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

output=np.dot(inputs,np.array(weights).T)+biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [9]:
inputs=[[1,2,3,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]

weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]

weights2=[[0.1,-0.14,0.5],
         [-0.5,0.12,-0.33],
         [-0.44,0.73,-0.13]]
biases2=[-1,2,-0.5]

layer1_outputs=np.dot(inputs,np.array(weights).T)+biases
layer2_outputs=np.dot(layer1_outputs,np.array(weights2).T)+biases2
print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [4]:
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]

np.random.seed(0)

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weigths=0.1*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output=np.dot(inputs,self.weigths)+self.biases
        
layer1=Layer_Dense(4,5)
layer2=Layer_Dense(5,2)

layer1.forward(X)
#print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [11]:
#Activation functions


In [12]:
#ReLU

In [2]:
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []
for i in inputs:
    if i>0:
        output.append(i)
    elif i<=0:
        output.append(0)
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [3]:
X=[[1,2,3,2.5],
   [2.0,5.0,-1.0,2.0],
   [-1.5,2.7,3.3,-0.8]]
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []
for i in inputs:
    output.append(max(0,i))

print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [5]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)        

In [7]:
!pip install nnfs
import nnfs

  Using cached nnfs-0.5.1-py3-none-any.whl (9.1 kB)


In [10]:
from nnfs.datasets import spiral_data
X,y = spiral_data(100, 3)

layer1=Layer_Dense(2,5)
activation1=Activation_ReLU()

layer1.forward(X)
activation1.forward(layer1.output)
print(activation1.output)

[[0.         0.         0.         0.         0.        ]
 [0.00044605 0.00112339 0.00136902 0.00233221 0.        ]
 [0.00088012 0.00214616 0.00282136 0.00444338 0.        ]
 ...
 [0.         0.         0.06718227 0.         0.        ]
 [0.         0.         0.         0.         0.01082432]
 [0.         0.         0.         0.         0.00870763]]


In [13]:
#SoftMax

In [16]:
import math
layer_outputs=[4.8, 1.21, 2.385]
E=math.e

exp_values=[]

for output in layer_outputs:
    exp_values.append(E**output)

print(exp_values)

norm_base=sum(exp_values)
norm_values=[]

for value in exp_values:
    norm_values.append(value/norm_base)
    
print(norm_values)

[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]


In [19]:
layer_outputs=[4.8, 1.21, 2.385]

exp_values=np.exp(layer_outputs)

norm_values=exp_values/np.sum(exp_values)
    
print(norm_values)

[0.89528266 0.02470831 0.08000903]


In [31]:
import math
layer_outputs=[[4.8, 1.21, 2.385],
               [8.9, -1.81, 0.2],
               [1.41, 1.051, 0.026]]

exp_values=np.exp(layer_outputs)
norm_values=exp_values/np.sum(exp_values,axis=1, keepdims=True)   
print(norm_values)

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [35]:
class Activation_Softmax:
    def forward(self,inputs):
        exp_values=np.exp(inputs-np.max(inputs,axis=1, keepdims=True))
        probabilities=exp_values/np.sum(exp_values,axis=1, keepdims=True)  
        self.output=probabilities        

In [38]:
X,y=spiral_data(100,3)

dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()
dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

[[0.33333333 0.33333333 0.33333333]
 [0.33330839 0.33334061 0.333351  ]
 [0.33334076 0.33332181 0.33333744]
 [0.33333661 0.33332824 0.33333515]
 [0.33325822 0.33334591 0.33339587]]


In [39]:
b=5.2
print(np.log(b))

1.6486586255873816


In [43]:
E**1.6486586255873818


5.2

In [49]:
softmax_output =[0.7,0.1,0.2]
target_output=[1,0,0]
loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])
print(loss)

loss=-math.log(softmax_output[0])
print(loss)

0.35667494393873245
0.35667494393873245
